import defaultMdxComponents from 'fumadocs-ui/mdx';
import type { MDXComponents } from 'mdx/types';
// 1. Import your button
import { PublisherButton } from '@/components/ros-ui/publisher-button';

// Note: Next.js App Router expects this function to be named 'useMDXComponents'
// If 'getMDXComponents' was generated by the template, rename it to 'useMDXComponents' to be safe.
export function getMDXComponents(components?: MDXComponents): MDXComponents {
  return {
    ...defaultMdxComponents,
    ...components,
    // 2. Register the component here
    PublisherButton,
  };
}